quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

quarkus.rest-client.geocoding.url=https://geocoding-api.open-meteo.com
quarkus.rest-client.openmeteo.url=https://api.open-meteo.com

quarkus.langchain4j.gpu-llama3.chat-model.model-name=unsloth/Llama-3.2-1B-Instruct-GGUF
quarkus.langchain4j.gpu-llama3.chat-model.quantization=F16
quarkus.langchain4j.gpu-llama3.chat-model.max-tokens=2048

#quarkus.langchain4j.ollama.chat-model.enabled=true
#quarkus.langchain4j.ollama.base-url=http://localhost:11434
#quarkus.langchain4j.ollama.chat-model.temperature=0.7
#quarkus.langchain4j.ollama.chat-model.model-id=llama3.2:1b-instruct-q8_0